export interface Question {
  id: number;
  question: string;
  options: string[];
  answerIdx: number;
  hint: string;
}

export const TRIVIA_QUESTIONS: Question[] = [
  { id: 1, question: 'What year was the iconic game "Pac-Man" first released in arcades?', options: ['1978', '1980', '1982', '1985'], answerIdx: 1, hint: 'It was the beginning of a new decade.' },
  { id: 2, question: 'In the classic game Snake, what happens when the snake eats food?', options: ['It speeds up only', 'It grows longer', 'The level restarts', 'It earns points only'], answerIdx: 1, hint: 'The challenge is managing your increasing size.' },
  { id: 3, question: 'Which console introduced the iconic D-pad (directional pad) to gaming?', options: ['Atari 2600', 'Sega Genesis', 'Nintendo Game & Watch', 'PlayStation'], answerIdx: 2, hint: 'It was a handheld device by a famous Japanese company.' },
  { id: 4, question: 'In Tic-Tac-Toe, how many possible winning lines are there on a 3×3 grid?', options: ['6', '8', '9', '12'], answerIdx: 1, hint: 'Count rows, columns, and diagonals.' },
  { id: 5, question: 'What is the term for the fastest possible reaction time a trained human can achieve?', options: ['~100 ms', '~200 ms', '~300 ms', '~400 ms'], answerIdx: 1, hint: 'Elite athletes can get close to this threshold.' },
  { id: 6, question: 'What is the best-selling video game console of all time?', options: ['PlayStation 2', 'Nintendo DS', 'Nintendo Switch', 'Xbox 360'], answerIdx: 0, hint: 'It was released by Sony in 2000.' },
  { id: 7, question: 'Which game features the character "Master Chief"?', options: ['Destiny', 'Doom', 'Halo', 'Gears of War'], answerIdx: 2, hint: 'He is also known as Spartan-117.' },
  { id: 8, question: 'What is the highest-grossing media franchise of all time?', options: ['Star Wars', 'Marvel Cinematic Universe', 'Pokémon', 'Mario'], answerIdx: 2, hint: 'Gotta catch em all!' },
  { id: 9, question: 'In Minecraft, what material do you need to mine to build a Nether Portal?', options: ['Diamond', 'Obsidian', 'Bedrock', 'Iron'], answerIdx: 1, hint: 'It is formed when water touches lava source blocks.' },
  { id: 10, question: 'What was Mario’s original name in his first arcade appearance?', options: ['Plumber Pete', 'Jumpman', 'Mr. Video', 'Luigi'], answerIdx: 1, hint: 'He liked to hop over barrels.' },
  { id: 11, question: 'Which company developed the game "Fortnite"?', options: ['Valve', 'Riot Games', 'Epic Games', 'Blizzard'], answerIdx: 2, hint: 'They also created the Unreal Engine.' },
  { id: 12, question: 'In which game do you play as Geralt of Rivia?', options: ['Elder Scrolls', 'Dragon Age', 'The Witcher', 'Dark Souls'], answerIdx: 2, hint: 'He is a monster hunter.' },
  { id: 13, question: 'What is the main currency in the "Legend of Zelda" series?', options: ['Coins', 'Rupees', 'Gil', 'Rings'], answerIdx: 1, hint: 'They share a name with a real-world currency in India.' },
  { id: 14, question: 'Which game popularized the "Battle Royale" genre before Fortnite?', options: ['H1Z1', 'PUBG', 'DayZ', 'Apex Legends'], answerIdx: 1, hint: 'PlayerUnknown is in the title.' },
  { id: 15, question: 'What color is the "B" button on an original Xbox controller?', options: ['Red', 'Green', 'Blue', 'Yellow'], answerIdx: 0, hint: 'It matches the color of a stop sign.' },
  { id: 16, question: 'Who is the main antagonist in the "Portal" series?', options: ['G-Man', 'GLaDOS', 'Wheatley', 'Dr. Breen'], answerIdx: 1, hint: 'She promises cake.' },
  { id: 17, question: 'Which video game holds the record for the most Game of the Year awards?', options: ['The Witcher 3', 'The Last of Us Part II', 'Elden Ring', 'God of War'], answerIdx: 2, hint: 'It was created by FromSoftware and George R.R. Martin.' },
  { id: 18, question: 'What is the name of the protagonist in the "Tomb Raider" series?', options: ['Lara Croft', 'Nathan Drake', 'Samus Aran', 'Jill Valentine'], answerIdx: 0, hint: 'She is a British archaeologist.' },
  { id: 19, question: 'Which game features the fictional language "Simlish"?', options: ['Animal Crossing', 'The Sims', 'Spore', 'Stardew Valley'], answerIdx: 1, hint: 'Sul sul!' },
  { id: 20, question: 'In League of Legends, what is the maximum level a champion can reach in a normal match?', options: ['18', '20', '30', '15'], answerIdx: 0, hint: 'It is the age of legal adulthood in many countries.' },
  { id: 21, question: 'Which game studio developed "Overwatch"?', options: ['Riot Games', 'Valve', 'Blizzard Entertainment', 'Bungie'], answerIdx: 2, hint: 'They also made World of Warcraft.' },
  { id: 22, question: 'What is the name of the princess you must save in Super Mario Bros?', options: ['Daisy', 'Peach', 'Zelda', 'Rosalina'], answerIdx: 1, hint: 'She is named after a fruit.' },
  { id: 23, question: 'Which of these is NOT a playable race in World of Warcraft?', options: ['Tauren', 'Draenei', 'Khajiit', 'Pandaren'], answerIdx: 2, hint: 'This race is from The Elder Scrolls series.' },
  { id: 24, question: 'What shape is a standard Tetris block consisting of four squares called?', options: ['Quadrom', 'Tetromino', 'Block', 'Pixel'], answerIdx: 1, hint: 'It sounds like the name of the game.' },
  { id: 25, question: 'Which character is known for saying "It’s a me!"?', options: ['Luigi', 'Wario', 'Mario', 'Toad'], answerIdx: 2, hint: 'He wears a red hat.' },
  { id: 26, question: 'What was the first commercially successful video game?', options: ['Space Invaders', 'Pong', 'Pac-Man', 'Asteroids'], answerIdx: 1, hint: 'It simulates table tennis.' },
  { id: 27, question: 'In the game "Among Us", what are the bad guys called?', options: ['Traitors', 'Killers', 'Impostors', 'Aliens'], answerIdx: 2, hint: 'They are sus.' },
  { id: 28, question: 'What is the name of the final boss in Minecraft?', options: ['The Wither', 'Ender Dragon', 'Warden', 'Herobrine'], answerIdx: 1, hint: 'It lives in the End.' },
  { id: 29, question: 'Which video game character is blue and collects rings?', options: ['Crash Bandicoot', 'Mega Man', 'Sonic the Hedgehog', 'Spyro'], answerIdx: 2, hint: 'Gotta go fast!' },
  { id: 30, question: 'What is the name of the city in "Grand Theft Auto V"?', options: ['Vice City', 'Liberty City', 'San Andreas', 'Los Santos'], answerIdx: 3, hint: 'It is based on Los Angeles.' },
  { id: 31, question: 'Which game involves building and defending your bed?', options: ['Roblox', 'Terraria', 'Bed Wars', 'Rust'], answerIdx: 2, hint: 'It is a popular Minecraft minigame.' },
  { id: 32, question: 'What animal is Tom Nook in Animal Crossing?', options: ['Raccoon', 'Tanuki', 'Bear', 'Dog'], answerIdx: 1, hint: 'It is a Japanese raccoon dog.' },
  { id: 33, question: 'Which of these games was created by a single developer?', options: ['Stardew Valley', 'Hollow Knight', 'Celeste', 'Terraria'], answerIdx: 0, hint: 'ConcernedApe is the developer.' },
  { id: 34, question: 'What does "NPC" stand for?', options: ['No Player Character', 'Non-Playable Character', 'New Player Character', 'Next Player Computer'], answerIdx: 1, hint: 'It is a character controlled by the game.' },
  { id: 35, question: 'In "God of War", what is Kratos’ son’s name?', options: ['Atreus', 'Ares', 'Zeus', 'Loki'], answerIdx: 0, hint: 'Boy!' },
  { id: 36, question: 'Which game features the phrase "War. War never changes."?', options: ['Call of Duty', 'Battlefield', 'Fallout', 'Gears of War'], answerIdx: 2, hint: 'It takes place in a post-apocalyptic wasteland.' },
  { id: 37, question: 'What is the name of the green dinosaur that Mario rides?', options: ['Bowser', 'Yoshi', 'Birdo', 'Rex'], answerIdx: 1, hint: 'He has a long tongue and eats apples.' },
  { id: 38, question: 'Which company makes the graphics cards known as "GeForce"?', options: ['AMD', 'Intel', 'Nvidia', 'Radeon'], answerIdx: 2, hint: 'Their logo is green.' },
  { id: 39, question: 'What is the max level in classic World of Warcraft (Vanilla)?', options: ['50', '60', '70', '100'], answerIdx: 1, hint: 'It is the number of minutes in an hour.' },
  { id: 40, question: 'Which fighting game features "Fatalities"?', options: ['Street Fighter', 'Tekken', 'Mortal Kombat', 'Super Smash Bros'], answerIdx: 2, hint: 'Finish him!' },
  { id: 41, question: 'What does "RPG" stand for in gaming?', options: ['Rapid Play Game', 'Role-Playing Game', 'Real Player Graphics', 'Random Play Generator'], answerIdx: 1, hint: 'You assume the role of a character.' },
  { id: 42, question: 'In the game "Hades", who is the protagonist?', options: ['Zeus', 'Ares', 'Zagreus', 'Poseidon'], answerIdx: 2, hint: 'He is the son of Hades.' },
  { id: 43, question: 'Which game popularized the "sandbox" genre?', options: ['Grand Theft Auto III', 'Minecraft', 'The Sims', 'Garry’s Mod'], answerIdx: 0, hint: 'It was released by Rockstar in 2001.' },
  { id: 44, question: 'What is the primary objective in "Rocket League"?', options: ['Race to the finish', 'Destroy other cars', 'Play soccer with cars', 'Collect coins'], answerIdx: 2, hint: 'It involves a giant ball and goals.' },
  { id: 45, question: 'Who is the creator of the "Metal Gear" series?', options: ['Shigeru Miyamoto', 'Hideo Kojima', 'Shinji Mikami', 'Hideki Kamiya'], answerIdx: 1, hint: 'He founded his own studio after leaving Konami.' },
  { id: 46, question: 'What color is Pac-Man?', options: ['Yellow', 'Orange', 'Red', 'Pink'], answerIdx: 0, hint: 'It is the color of a lemon.' },
  { id: 47, question: 'Which video game features the "Creeper"?', options: ['Terraria', 'Roblox', 'Minecraft', 'Fortnite'], answerIdx: 2, hint: 'It explodes when it gets near you.' },
  { id: 48, question: 'What is the name of the protagonist in "The Legend of Zelda"?', options: ['Zelda', 'Link', 'Ganon', 'Sheik'], answerIdx: 1, hint: 'He wears a green tunic.' },
  { id: 49, question: 'Which game is famous for the phrase "The cake is a lie"?', options: ['Half-Life 2', 'Portal', 'Team Fortress 2', 'Left 4 Dead'], answerIdx: 1, hint: 'It involves thinking with portals.' },
  { id: 50, question: 'What is the highest-selling video game of all time (as of 2024)?', options: ['Tetris', 'Grand Theft Auto V', 'Minecraft', 'Wii Sports'], answerIdx: 2, hint: 'It involves breaking and placing blocks.' },
  { id: 51, question: 'Which of these is a popular MOBA game?', options: ['Counter-Strike', 'League of Legends', 'World of Warcraft', 'Overwatch'], answerIdx: 1, hint: 'It is developed by Riot Games.' },
  { id: 52, question: 'What does "FPS" stand for in terms of game genre?', options: ['Frames Per Second', 'First-Person Shooter', 'Fast Playing System', 'Free Play Server'], answerIdx: 1, hint: 'You view the game through the eyes of the character.' },
  { id: 53, question: 'Which game features a battle royale mode called "Warzone"?', options: ['Battlefield', 'Call of Duty', 'Apex Legends', 'PUBG'], answerIdx: 1, hint: 'It is a spin-off of the Modern Warfare series.' },
  { id: 54, question: 'Who is Mario’s brother?', options: ['Wario', 'Toad', 'Luigi', 'Yoshi'], answerIdx: 2, hint: 'He wears green.' },
  { id: 55, question: 'What company created the PlayStation?', options: ['Microsoft', 'Nintendo', 'Sega', 'Sony'], answerIdx: 3, hint: 'They are a massive Japanese conglomerate.' },
  { id: 56, question: 'Which game features the continent of Tamriel?', options: ['The Witcher', 'World of Warcraft', 'The Elder Scrolls', 'Dragon Age'], answerIdx: 2, hint: 'Skyrim is a province in this continent.' },
  { id: 57, question: 'What is the name of the main character in "Red Dead Redemption 2"?', options: ['John Marston', 'Arthur Morgan', 'Dutch van der Linde', 'Micah Bell'], answerIdx: 1, hint: 'He is a member of the Van der Linde gang.' },
  { id: 58, question: 'Which game involves drawing and guessing words with friends?', options: ['Jackbox', 'Skribbl.io', 'Among Us', 'Fall Guys'], answerIdx: 1, hint: 'It is a browser-based game.' },
  { id: 59, question: 'What is the name of the virtual reality headset made by Valve?', options: ['Oculus Rift', 'HTC Vive', 'Valve Index', 'PlayStation VR'], answerIdx: 2, hint: 'It comes with the "Knuckles" controllers.' },
  { id: 60, question: 'Which game features the song "Megalovania"?', options: ['Undertale', 'Celeste', 'Hollow Knight', 'Cuphead'], answerIdx: 0, hint: 'It plays during the fight with Sans.' },
  { id: 61, question: 'What is the max level in Pokémon?', options: ['50', '99', '100', '255'], answerIdx: 2, hint: 'It is a perfect century.' },
  { id: 62, question: 'Which console featured the game "Wii Sports"?', options: ['GameCube', 'Nintendo Wii', 'Wii U', 'Nintendo Switch'], answerIdx: 1, hint: 'It introduced motion controls to the mainstream.' },
  { id: 63, question: 'What is the name of the first Pokémon in the Pokédex?', options: ['Pikachu', 'Charmander', 'Bulbasaur', 'Squirtle'], answerIdx: 2, hint: 'It is a Grass/Poison type.' },
  { id: 64, question: 'Which game features the character "Kratos"?', options: ['Devil May Cry', 'God of War', 'Assassin’s Creed', 'Dark Souls'], answerIdx: 1, hint: 'He is the Ghost of Sparta.' },
  { id: 65, question: 'What does "HUD" stand for in gaming?', options: ['Heads Up Display', 'High User Definition', 'Hard User Difficulty', 'Hidden Underground Dungeon'], answerIdx: 0, hint: 'It shows your health, ammo, and map on the screen.' },
  { id: 66, question: 'Which game involves surviving nights against animatronics?', options: ['Amnesia', 'Slender', 'Five Nights at Freddy’s', 'Outlast'], answerIdx: 2, hint: 'You play as a security guard.' },
  { id: 67, question: 'What is the name of the main currency in "Roblox"?', options: ['Robux', 'Tix', 'Coins', 'V-Bucks'], answerIdx: 0, hint: 'It sounds like the name of the game.' },
  { id: 68, question: 'Which game features the character "Tracer"?', options: ['Valorant', 'Apex Legends', 'Overwatch', 'Paladins'], answerIdx: 2, hint: 'She can rewind time.' },
  { id: 69, question: 'What is the name of the sword used by Link in "The Legend of Zelda"?', options: ['Buster Sword', 'Master Sword', 'Keyblade', 'Energy Sword'], answerIdx: 1, hint: 'It is the blade of evil’s bane.' },
  { id: 70, question: 'Which game features the "Lombax" race?', options: ['Jak and Daxter', 'Sly Cooper', 'Ratchet & Clank', 'Crash Bandicoot'], answerIdx: 2, hint: 'The main character uses a wrench.' },
  { id: 71, question: 'What is the highest rarity tier in Fortnite?', options: ['Legendary', 'Epic', 'Mythic', 'Exotic'], answerIdx: 2, hint: 'They are usually dropped by bosses.' },
  { id: 72, question: 'Which game features the phrase "Praise the Sun"?', options: ['Elden Ring', 'Dark Souls', 'Bloodborne', 'Sekiro'], answerIdx: 1, hint: 'It is associated with Solaire of Astora.' },
  { id: 73, question: 'What is the name of the blue shell in Mario Kart that targets first place?', options: ['Spiny Shell', 'Homing Shell', 'Blue Turtle', 'Leader Shell'], answerIdx: 0, hint: 'It has spikes on it.' },
  { id: 74, question: 'Which game involves managing a vault in a post-apocalyptic world?', options: ['Fallout Shelter', 'SimCity', 'RimWorld', 'Oxygen Not Included'], answerIdx: 0, hint: 'It is a mobile spin-off of a popular RPG series.' },
  { id: 75, question: 'What is the name of the protagonist in "Persona 5"?', options: ['Yu Narukami', 'Makoto Yuki', 'Ren Amamiya (Joker)', 'Ryuji Sakamoto'], answerIdx: 2, hint: 'He is the leader of the Phantom Thieves.' },
  { id: 76, question: 'Which game features the "V-Bucks" currency?', options: ['Apex Legends', 'Fortnite', 'PUBG', 'Valorant'], answerIdx: 1, hint: 'It stands for Vindertech Bucks.' },
  { id: 77, question: 'What is the name of the alien race in "Halo"?', options: ['The Hive', 'The Covenant', 'The Zerg', 'The Flood'], answerIdx: 1, hint: 'They are a religious hegemony.' },
  { id: 78, question: 'Which game features the character "Ezio Auditore"?', options: ['Hitman', 'Dishonored', 'Assassin’s Creed', 'Thief'], answerIdx: 2, hint: 'He operates in Renaissance Italy.' },
  { id: 79, question: 'What does "AFK" stand for?', options: ['A Free Kill', 'Away From Keyboard', 'Always For Kicks', 'Action For Kids'], answerIdx: 1, hint: 'It means the player is not currently playing.' },
  { id: 80, question: 'Which game involves slicing fruit like a ninja?', options: ['Fruit Ninja', 'Cooking Mama', 'Beat Saber', 'Cut the Rope'], answerIdx: 0, hint: 'It was a massive hit on early smartphones.' },
  { id: 81, question: 'What is the name of the planet where "Final Fantasy VII" takes place?', options: ['Spira', 'Gaia', 'Eos', 'Ivalice'], answerIdx: 1, hint: 'It shares its name with the Greek personification of the Earth.' },
  { id: 82, question: 'Which game features the character "Steve"?', options: ['Roblox', 'Terraria', 'Minecraft', 'Garry’s Mod'], answerIdx: 2, hint: 'He wears a blue shirt and jeans.' },
  { id: 83, question: 'What is the name of the evil doctor in the Sonic the Hedgehog series?', options: ['Dr. Wily', 'Dr. Eggman (Robotnik)', 'Dr. Cortex', 'Dr. Nefarious'], answerIdx: 1, hint: 'He loves machines and hates a certain hedgehog.' },
  { id: 84, question: 'Which game features the "BFG 9000"?', options: ['Quake', 'Halo', 'Doom', 'Duke Nukem'], answerIdx: 2, hint: 'It stands for Big F***ing Gun.' },
  { id: 85, question: 'What is the name of the princess in the "Mario" franchise?', options: ['Zelda', 'Peach', 'Daisy', 'Rosalina'], answerIdx: 1, hint: 'She rules the Mushroom Kingdom.' },
  { id: 86, question: 'Which game involves throwing birds at pigs?', options: ['Flappy Bird', 'Angry Birds', 'Crossy Road', 'Tiny Wings'], answerIdx: 1, hint: 'They are furious.' },
  { id: 87, question: 'What is the name of the protagonist in "The Witcher"?', options: ['Vesemir', 'Lambert', 'Geralt', 'Eskel'], answerIdx: 2, hint: 'He is known as the White Wolf.' },
  { id: 88, question: 'Which game features the "Diamond Pickaxe"?', options: ['Terraria', 'Stardew Valley', 'Minecraft', 'Animal Crossing'], answerIdx: 2, hint: 'It is highly durable and mines obsidian.' },
  { id: 89, question: 'What does "PvE" stand for?', options: ['Player vs Everyone', 'Player vs Environment', 'Player vs Enemy', 'Play vs Earn'], answerIdx: 1, hint: 'You fight AI, not other players.' },
  { id: 90, question: 'Which game features the "Ghost" as a companion?', options: ['Halo', 'Destiny', 'Mass Effect', 'Warframe'], answerIdx: 1, hint: 'It is a small, floating AI companion voiced by Nolan North (originally Peter Dinklage).' },
  { id: 91, question: 'What is the name of the city in "Cyberpunk 2077"?', options: ['Neo Tokyo', 'Night City', 'Midgar', 'Los Santos'], answerIdx: 1, hint: 'It never sleeps.' },
  { id: 92, question: 'Which game features the "Fatality" finishing move?', options: ['Street Fighter', 'Tekken', 'Mortal Kombat', 'Injustice'], answerIdx: 2, hint: 'Finish him!' },
  { id: 93, question: 'What is the name of the main character in "Tomb Raider"?', options: ['Nathan Drake', 'Lara Croft', 'Aloy', 'Ellie'], answerIdx: 1, hint: 'She is an archaeologist.' },
  { id: 94, question: 'Which game involves building factories on an alien planet?', options: ['Satisfactory', 'Factorio', 'RimWorld', 'Oxygen Not Included'], answerIdx: 1, hint: 'The factory must grow.' },
  { id: 95, question: 'What is the name of the company that created the "Super Smash Bros" series?', options: ['Sega', 'Capcom', 'Nintendo', 'Bandai Namco'], answerIdx: 2, hint: 'They also created Mario and Zelda.' },
  { id: 96, question: 'Which game features the "Aperture Science Handheld Portal Device"?', options: ['Half-Life', 'Portal', 'Team Fortress 2', 'Quantum Conundrum'], answerIdx: 1, hint: 'It shoots orange and blue portals.' },
  { id: 97, question: 'What is the name of the dragon you fight in "Skyrim"?', options: ['Smaug', 'Deathwing', 'Alduin', 'Paarthurnax'], answerIdx: 2, hint: 'He is the World-Eater.' },
  { id: 98, question: 'Which game features the "Master Sword"?', options: ['Fire Emblem', 'The Legend of Zelda', 'Final Fantasy', 'Dragon Quest'], answerIdx: 1, hint: 'It is wielded by Link.' },
  { id: 99, question: 'What is the name of the main character in "Halo"?', options: ['Marcus Fenix', 'Master Chief', 'Doomguy', 'Captain Price'], answerIdx: 1, hint: 'He is Spartan-117.' },
  { id: 100, question: 'Which game involves jumping out of a "Battle Bus"?', options: ['PUBG', 'Apex Legends', 'Fortnite', 'Call of Duty: Warzone'], answerIdx: 2, hint: 'It drops you onto the island.' },
];
